import type { TableConfig } from '$lib/stores/table.svelte';

function line(x1: number, y1: number, x2: number, y2: number, layer = '0'): string {
	return `0
LINE
8
${layer}
10
${x1}
20
${y1}
30
0
11
${x2}
21
${y2}
31
0
`;
}

function text(x: number, y: number, height: number, content: string, layer = '0'): string {
	return `0
TEXT
8
${layer}
10
${x}
20
${y}
30
0
40
${height}
1
${content}
`;
}

function rect(x: number, y: number, w: number, h: number, layer = '0'): string {
	return (
		line(x, y, x + w, y, layer) +
		line(x + w, y, x + w, y + h, layer) +
		line(x + w, y + h, x, y + h, layer) +
		line(x, y + h, x, y, layer)
	);
}

export function exportDXF(config: TableConfig): void {
	const { width, depth, legTube } = config;
	const legW = legTube.width;
	const legH = legTube.height;

	let entities = '';

	// Outer table footprint
	entities += rect(0, 0, width, depth, 'TABLE');

	// Leg rectangles at corners
	// Bottom-left
	entities += rect(0, 0, legW, legH, 'LEGS');
	// Bottom-right
	entities += rect(width - legW, 0, legW, legH, 'LEGS');
	// Top-left
	entities += rect(0, depth - legH, legW, legH, 'LEGS');
	// Top-right
	entities += rect(width - legW, depth - legH, legW, legH, 'LEGS');

	// Dimension text labels
	const textH = Math.max(1, Math.min(width, depth) * 0.04);
	entities += text(width / 2 - textH * 2, -textH * 2, textH, `${width}"`, 'DIMS');
	entities += text(-textH * 4, depth / 2, textH, `${depth}"`, 'DIMS');
	entities += text(width / 2 - textH * 3, depth / 2, textH, `H: ${config.height}"`, 'DIMS');

	const dxf = `999
DXF generated by Tubular
0
SECTION
2
ENTITIES
${entities}0
ENDSEC
0
EOF
`;

	const blob = new Blob([dxf], { type: 'application/dxf' });
	const url = URL.createObjectURL(blob);
	const a = document.createElement('a');
	a.href = url;
	a.download = 'tubular-plan.dxf';
	a.click();
	URL.revokeObjectURL(url);
}
